name: Build macOS Application

on:
  push:
    tags: ['v*']
  workflow_dispatch:  # 允许手动触发

jobs:
  build-macos:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Build macOS application
      run: |
        pyinstaller --onefile --windowed --name "MyApp" your_script.py
        
    - name: Create DMG package (可选)
      run: |
        pip install dmgbuild
        # 创建安装包
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: macOS-Application
        path: dist/
        retention-days: 30