name: Build All Platforms

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-all:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            name: linux
          - os: windows-latest
            name: windows
          - os: macos-latest
            name: macos

    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      shell: bash  # 关键修复：强制使用 bash
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Build executable
      shell: bash  # 关键修复：强制使用 bash
      run: |
        pyinstaller --onefile --name "myapp-${{ matrix.name }}" fialiaoi-cpp.py
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: myapp-${{ matrix.name }}
        path: dist/myapp-${{ matrix.name }}*
