name: Build macOS Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # 允许手动触发

jobs:
  build-macos:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        # 安装项目依赖
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Build macOS executable
      run: |
        # 为你的 Python 文件构建可执行文件
        pyinstaller --onefile --name "my-macos-app" fallaoi-cpp.py
        
    - name: Upload macOS binary
      uses: actions/upload-artifact@v4
      with:
        name: macOS-Application
        path: dist/my-macos-app
        retention-days: 30
