name: Create Multi-Platform Release

on:
  push:
    tags: ['v*']
  workflow_dispatch:

jobs:
  build-releases:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            name: linux
            ext: ""
          - os: windows-latest
            name: windows
            ext: ".exe"
          - os: macos-latest
            name: macos
            ext: ""

    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        pip install pyinstaller
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Build executable
      run: |
        pyinstaller --onefile --name "myapp-${{ matrix.name }}" fialiaoi-cpp.py
        
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: myapp-${{ matrix.name }}${{ matrix.ext }}
        path: dist/myapp-${{ matrix.name }}*
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: dist/myapp-${{ matrix.name }}*
